--- 
- hosts: localhost
  connection: local
  become: true

  tasks:
  - block: # stow dotfiles
    - name: create projects folder (if not exist)
      become_user: sawyer
      file:
        path: ~/projects
        state: directory
        owner: sawyer
        
    - name: clone .dotfiles
      become_user: sawyer
      git:
        # repo: "git@github.com:LegitCamper/.dotfiles.git"
        repo: "https://github.com/LegitCamper/.dotfiles.git"
        dest: ~/projects/.dotfiles
        clone: yes
        update: yes
  
    - name: stow dotfiles
      become_user: sawyer
      shell:
        chdir: ~/projects/.dotfiles
        cmd: nix-shell -p stow --run "stow -t ~ --adopt -S terminals editors shells hyprlandwm && git restore ."

    - name: create ssh folder (if not exist)
      become_user: sawyer
      file:
        path: ~/.ssh
        state: directory
        owner: sawyer
  
    - name: copy and decrypt keys (if needed)
      become_user: sawyer
      copy:
        src: "../{{ item.src }}"
        dest: "{{ item.dest }}"
        decrypt: yes
        owner: sawyer
        mode: 0600
      loop:
        - src: ssh_key
          dest: ~/.ssh/id_ed25519
        - src: ssh_key.pub
          dest: ~/.ssh/id_ed25519.pub
        - src: editors/.wakatime.cfg        
          dest: ~/.wakatime.cfg
        - src: editors/.config/github-copilot/hosts.json
          dest: ~/.config/github-copilot/hosts.json

  # - block: # configures nix
  #   - name: congure nix system
  #     become_user: sawyer
  #     shell: 
  #       chdir: ~/projects/.dotfiles/nix/system
  #       cmd: rm -rf /etc/nixos/configuration.nix && ln -s configuration.nix /etc/nixos/configuration.nix && sudo nixos-rebuild switch 
        
  #   - name: congure home-manager
  #     become_user: sawyer
  #     shell: 
  #       chdir: ~/projects/.dotfiles/nix/home
  #       cmd: mkdir ~/.config/home-manager/ && ln -s default.nix ~/.conifg/home-manager/home.nix && home-manager build 

  - block: # setup auto updater
    - name: add ansible user
      user: name=ansible uid=900

    - name: install cron job (ansible-pull)
      cron: user="ansible" name="ansible provision" minute="*/10" job="/usr/bin/ansible-pull -o -U https://github.com/LegitCamper/.dotfiles.git > /dev/null"
