[[language]]
name = "python"
roots = ["pyproject.toml"]
language-server = { command = "ruff-lsp" }
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "rust"
language-server = { command = "rustup", args = [
  "run",
  "stable",
  "rust-analyzer",
] }
formatter = { command = "clippy" }
file-types = ["rs"]
auto-format = true

[[language]]
name = "go"
language-server = { command = "gopls" }
formatter = { command = "gofmt" }
file-types = ["go"]
auto-format = true

[[language]]
name = "toml"
language-server = { command = "taplo", args = ["lsp", "stdio"] }
# formatter = { command = "taplo", args = ["format"] }
file-types = ["toml"]
scope = "text.toml"
comment-token = "#"
auto-format = true

[[language]]
name = "nix"
formatter = { command = "nixfmt" }
file-types = ["nix", "flake"]
roots = ["flake.lock"]
comment-token = "#"
auto-format = true

[[language]]
name = "ansible"
language-server = { command = "ansible-language-server", args = ["--stdio"] }
file-types = ["yml", "yaml"]
roots = ["local.yml", "local.yaml"]
scope = "text.ansible"
comment-token = "#"
auto-format = true

[[language]]
name = "lua"
language-server = { command = "lua-language-server" }
formatter = { command = "lua-format" }
file-types = ["lua"]
comment-token = "--"
auto-format = true
