--- 
- hosts: localhost
  connection: local
  become: true

  tasks:
  - block: # packages
    - name: install packages all
      when: ansible_distribution in [ "Archlinux" ]
      package:
        name:
          - stow
          - alacritty
          - kitty
          - solaar
          - exa
          - fd
          - ripgrep
          - fish
          - htop
          - git
          - python3
          - go
          - npm
          - ninja
          - gcc
          - docker
          - neovim
          - lazygit
          - flameshot
          - swaylock
          - swayidle
          - swaybg
          - wofi
          - rofi
          - dunst
          - pipewire
          - pipewire-alsa
          - wireplumber
          - jq
          - playerctl
          - hyprland
          - waybar
          - grim
          - slurp
          - fzf
          - cmake
          - pavucontrol
          - lxappearance
          - ttf-ubuntu-mono-nerd
          - pipewire-pulse
          - mpc
          - light
          - network-manager-applet
          - cronie
  
    - name: install packages debian
      when: ansible_distribution in [ "Debian", "Pop!_OS", "Ubuntu" ]
      package:
        name:
          - None
          
  - block: # stow dotfiles
    - name: create projects folder (if not exist)
      become_user: sawyer
      file:
        path: ~/projects
        state: directory
        owner: sawyer
        group: sawyer
        
    - name: copy .dotfiles
      become_user: sawyer
      copy:
        src: ~/.ansible/tmp/.dotfiles
        dest: ~/projects/.dotfiles
  
    - name: stow dotfiles
      become_user: sawyer
      shell: bash -c '~/projects/.dotfiles/.stow.sh'
  
    - name: copy and decrypt keys (if needed)
      become_user: sawyer
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        decrypt: yes
        owner: sawyer
        group: sawyer
        mode: 0600
      loop:
        - src: ssh_key
          dest: ~/.ssh/id_ed25519
        - src: ssh_key.pub
          dest: ~/.ssh/id_ed25519.pub
          
  - block: # setup auto updater
    - name: add ansible user
      user: name=ansible uid=900

    - name: install cron job (ansible-pull)
      cron: user="ansible" name="ansible provision" minute="*/10" job="/usr/bin/ansible-pull -o -U https://github.com/LegitCamper/.dotfiles.git > /dev/null"
  
  
