--- 
- hosts: localhost
  connection: local
  become: true

  tasks:
    - include: tasks/plugins.yml # installs ansible plugins
    - include: tasks/users.yml # configs users for ansible tasks
    - include: tasks/packages.yml # installs packages
    - include: tasks/services.yml # configs a cron task to auto update system
    - include: tasks/configs.yml # configs desktop related files and themes
    # running services again with new configs
    - include: tasks/pull.yml # configs a cron task to auto update system
