--- 
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: install ansible modules
      ansible.builtin.include_tasks:
        file: tasks/plugins.yml # installs ansible plugins 

  tasks:
    - name: Include task list in play
      loop:
        - tasks/packages.yml # installs packages
        - tasks/snapshot.yml # creates snapshot before modifications
        - tasks/users.yml # configs users for ansible tasks
        - tasks/services.yml # configs a cron task to auto update system      
        - tasks/configs.yml # configs desktop related files and themes
      ansible.builtin.include_tasks:
        file: "{{ item }}"
