---
- hosts: localhost
  connection: local

  pre_tasks:
    - name: confirm running as root
      become: true
      command: id -u
      register: id_output
    - assert:
        that: id_output.stdout == '0'

    - name: install ansible modules
      ansible.builtin.include_tasks:
        file: tasks/plugins.yml # installs ansible plugins

    - set_fact:
        packages_installed: false

    - name: create users
      ansible.builtin.include_tasks:
        file: tasks/users.yml

  tasks:
    - name: Include task list in play
      loop:
        - tasks/packages.yml # installs packages
        - tasks/users.yml # add user to package groups
        - tasks/configs.yml # configs desktop related files and themes
        - tasks/services.yml # configs a cron task to auto update system
      loop_control:
        loop_var: task
      ansible.builtin.include_tasks:
        file: "{{ task }}"
