---
# THIS SCRIPT IS INTENDED TO BE RAN INSIDE A TOOLBOX CONTAINER
- hosts: localhost
  connection: local
  ignore_unreachable: true
  become: true
  vars_files:
    - packages.yml

  pre_tasks:
    - name: create projects folder (if not exist)
      file:
        path: ~/projects
        state: directory

    - name: create ssh directory (if not exist)
      file:
        path: ~/.ssh
        state: directory

  tasks:
    - name: clone .dotfile
      git:
        repo: "https://github.com/LegitCamper/.dotfiles.git"
        dest: ~/projects/.dotfiles
        clone: yes
        update: no

    - name: stow dotfiles
      shell: stow -t ~ --adopt -S dots
      check_mode: false
      changed_when: false
      failed_when: false

    - name: copy and decrypt keys (if needed)
      with_items:
        - src: ./dots/ssh_key
          dest: ~/.ssh/id_ed25519
        - src: ./dots/ssh_key.pub
          dest: ~/.ssh/id_ed25519.pub
      loop_control:
        loop_var: ssh_file
      copy:
        src: "{{ ssh_file.src }}"
        dest: "{{ ssh_file.dest }}"
        decrypt: yes
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: 0600
