import os
from libqtile import bar, widget, qtile
from libqtile.config import Screen

from .colors import colors

screens = [
    Screen(
        top=bar.Bar(
            [
                widget.Sep(
                    linewidth=0,
                    padding=12,
                    foreground=colors['Background'],
                    Background=colors['Background']
                ),
                widget.TextBox(
                    text="",
                    padding=5,
                    fontsize=30,
                    foreground=colors['Purple'],
                    background=colors['Background']
                ),
                widget.GroupBox(
                    font="Font Awesome 6 Free Solid",
                    highlight_method="line",
                    highlight_color=colors["Background"],
                    rounded=False,
                    padding_x=5,
                    padding_y=4,
                    active=colors["Purple"],
                    inactive="#7c818c",
                    this_current_screen_border=colors["Pink"],
                    urgent_border=colors["Red"],
                    disable_drag=True,
                    margin_y=3,
                    spacing=4,
                    use_mouse_wheel=False
                    #hide_unused=True
                ),
                widget.Sep(
                    linewidth=0,
                    padding=10
                ),
                widget.CurrentLayoutIcon(
                    scale=0.65
                ),
                widget.Sep(
                    linewidth=0,
                    size_percent=60,
                    padding=12,
                    foreground=colors["Foreground"]
                ),
                widget.WindowName(
                    padding=5,
                    background=colors['Background'],
                    foreground=colors['Foreground'],
                    empty_group_string="Desktop",
                    max_chars=130,
                ),
                widget.Sep(
                    linewidth=0,
                    padding=16
                ),
                widget.Prompt(
                    foreground=colors["Cyan"]
                ),
                widget.TextBox(
                    font="Font Awesome 6 Free Solid",
                    fontsize=15,
                    foreground=colors["Purple"],
                    text="",
                    padding=12
                ),
                widget.Clock(
                    format="%a %b %d",
                    foreground=colors["Foreground"]
                ),
                widget.TextBox(
                    font="Font Awesome 6 Free Solid",
                    fontsize=15,
                    foreground=colors["Green"],
                    text="",
                    padding=12
                ),
                widget.Clock(
                    format='%I:%M:%p',
                    foreground=colors["Foreground"],
                    fontsize=15
                ),
                widget.Sep(
                    linewidth=0,
                    size_percent=60,
                    padding=12,
                    foreground=colors["Foreground"]
                ),
                widget.Spacer(),
                widget.TextBox(
                    background=colors["Background"],
                    foreground=colors["Orange"],
                    text="",
                    font="Font Awesome 6 Free Solid",
                    fontsize=15,
                ),
                widget.Net(
                    background=colors["Background"],
                    foreground=colors["Foreground"],
                    format="{down}"
                ),
                widget.Sep(
                    linewidth=0,
                    size_percent=60,
                    padding=16,
                    foreground=colors["Foreground"]
                ),
                widget.TextBox(
                    background=colors["Background"],
                    foreground=colors["Pink"],
                    text="",
                    font="Font Awesome 6 Free Solid",
                    fontsize=15,
                ),
                widget.CPU(
                    background=colors["Background"],
                    foreground=colors["Foreground"],
                    update_interval=1,
                    format="{load_percent: .0f} %",
                    fontsize=15,
                ),
                widget.Sep(
                    linewidth=0,
                    size_percent=60,
                    padding=16,
                    foreground=colors["Foreground"]
                ),
                widget.TextBox(
                    text="",
                    font="Font Awesome 6 Free Solid",
                    background=colors["Background"],
                    foreground=colors["Purple"],
                    fontsize=15,
                ),
                widget.Memory(
                    background=colors["Background"],
                    foreground=colors["Foreground"],
                    format="{MemPercent: .0f} %",
                    fontsize=15,
                ),
                widget.Sep(
                    linewidth=0,
                    size_percent=60,
                    padding=16,
                    foreground=colors["Foreground"]
                ),
                widget.TextBox(
                    font="Font Awesome 6 Free Solid",
                    fontsize=15,
                    foreground=colors["Cyan"],
                    text="",
                    padding=12
                ), 
                widget.Battery(
                    foreground=colors["Foreground"],
                    low_foreground=colors["Red"],
                    low_percentage=0.25,
                    format="{percent:2.0%}"
                ),
                widget.Sep(
                    linewidth=0,
                    size_percent=60,
                    padding=16,
                    foreground=colors["Foreground"]
                ),
                widget.TextBox(
                    font="Font Awesome 6 Free Solid",
                    fontsize=15,
                    foreground=colors["Yellow"],
                    text="",
                    padding=12
                ),    
                widget.PulseVolume(
                    foreground=colors["Foreground"],
                    limit_max_volume="True",
                    update_interval=0.02,
                ),
                widget.Sep(
                    linewidth=0,
                    size_percent=60,
                    padding=16,
                    foreground=colors["Foreground"]
                ),
                widget.Sep(
                    linewidth=0,
                    size_percent=60,
                    padding=16,
                    foreground=colors["Foreground"]
                ),
                widget.Systray(
                    icon_size=24,
                    background=colors["Background"]
                ),
                widget.Sep(
                    linewidth=0,
                    size_percent=60,
                    padding=12,
                    foreground=colors["Foreground"]
                ),
                widget.QuickExit(
                    background=colors['Background'],
                    foreground=colors['Red'],
                    default_text="",
                    fontsize=15,
                    padding=5,
                    countdown_start=5,
                    countdown_format="",
                ),
                widget.Sep(
                    linewidth=0,
                    padding=12,
                    foreground=colors['Background'],
                    background=colors['Background']
                )
            ],
            34,
            border_width=[0, 0, 3, 0],
            border_color=colors["Current Line"],
            background=colors["Background"],
            opacity = 1,
            margin=[0, 0, 0, 0]
        )
    ),
]
