add_newline = true
format = '''
$username@$hostname: 
$shell $directory\$ '''

right_format = '''
$cmd_duration
'''

[cmd_duration]
format="took [$duration]($style)"

[directory]
read_only = " "
truncation_length = 5
truncate_to_repo = true
truncation_symbol = '…/'
home_symbol = '~'

[hostname]
ssh_only = false
format = "[$hostname]($style)"

[username]
show_always = true
format = "[$user]($style)"

[shell]
fish_indicator = "🐟"
nu_indicator = "nu"
bash_indicator = "bash"
zsh_indicator = "zsh"
powershell_indicator = "_"
unknown_indicator = "mystery shell"
format = "$indicator"
disabled = false
