- name: set gtk theme
  become_user: sawyer
  shell: |
    gsettings set org.gnome.desktop.interface gtk-theme \
    "Catppuccin-Macchiato-Standard-Lavender-Dark"

- name: set icon theme
  become_user: sawyer
  shell: |
    gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"

- name: create projects folder (if not exist)
  become_user: sawyer
  file:
    path: ~/projects
    state: directory
    owner: sawyer
    group: sawyer

- name: clone .dotfiles
  become_user: sawyer
  git:
    repo: "https://github.com/LegitCamper/.dotfiles.git"
    dest: ~/projects/.dotfiles
    clone: yes
    update: no

- name: stow dotfiles
  become_user: sawyer
  shell: |
    ~/projects/.dotfiles/.stow.sh
    exit 0
  args:
    executable: /bin/bash

- name: copy and decrypt keys (if needed)
  become_user: sawyer
  with_items:
    - src: ssh_key
      dest: ~/.ssh/id_ed25519
    - src: ssh_key.pub
      dest: ~/.ssh/id_ed25519.pub
  loop_control:
    loop_var: ssh_file
  copy:
    src: "{{ ssh_file.src }}"
    dest: "{{ ssh_file.dest }}"
    decrypt: yes
    owner: sawyer
    group: sawyer
    mode: 0600

- name: login manager config
  become_user: root
  shell: |
    if ! grep -Fxq "Hyprland" /etc/greetd/config.toml; then
      cat /home/sawyer/projects/.dotfiles/tasks/files/greetd_config.toml \
      >> /etc/greetd/config.toml
    fi
  args:
    executable: /bin/bash

- name: configure u2f as alternative athentication method
  become_user: root
  with_items:
    - sudo
    - greetd
  loop_control:
    loop_var: u2f_file
  shell: |
    if ! grep -qs "pam_u2f" /etc/pam.d/{{ u2f_file }}; then
        u2f="auth sufficient pam_u2f.so cue origin=pam://$(hostname) appid=pam://$(hostname)"
        sed -i "2i$u2f" /etc/pam.d/{{ u2f_file }}
        sed -i -e 's/required/include/g' /etc/pam.d/{{ u2f_file }}
        sed -i -e 's/requisite/include/g' /etc/pam.d/{{ u2f_file }}
    fi
  args:
    executable: /bin/bash

- name: replace line for btrfs timeshift conf
  lineinfile:
    path: /usr/lib/systemd/system/grub-btrfsd.service
    regexp: "^ExecStart"
    line: "ExecStart=/usr/bin/grub-btrfsd --syslog --timeshift-auto"
    backrefs: yes

- name: rebuild grub conf
  become_user: root
  shell: grub-mkconfig -o /boot/grub/grub.cfg
