- name: packages declaration
  set_fact:
    packages:
      window_manager:
        - ttf-jetbrains-mono-nerd
        - hyprland
        - pyprland
        - xdg-desktop-portal-hyprland
        - waybar
        - greetd
        - greetd-tuigreet
        - flameshot
        - lxqt-qtplugin
        - papirus-icon-theme
        - lxappearance
        - dolphin
        - pavucontrol
        - blueman
        - swayidle
        - swaybg
        - wofi
        - dunst
        - playerctl
        - waybar
        - grim
        - slurp
        - wl-clipboard
        - socat
        - brightnessctl
        - moreutils # sponge...
        - efibootmgr
        - usbutils # lsusb
        - inotify-tools # dep for grub-btrfs
        - cronie
        - timeshift
        - grub-btrfs
        - udisks2
        - udiskie
      networking_tools:
        - networkmanager
        - network-manager-applet
        - inetutils # hostname ping ifconfig...
        - dnsutils # dig nslookup...
        - bridge-utils # brctl
        - nmap
      apps:
        - bitwarden
        - dolphin
        - ark
        - kate
        - gwenview
        - kcalc
        - rhythmbox
        - socat
        - qemu
        - libreoffice
        - vlc
        - ffmpeg
        - procs
        - solaar
        - discord
        - vivaldi
        - vivaldi-ffmpeg-codecs
        - obsidian
      gaming:
        - gamescope
        - lutris
        - steam
        - gamemode
        - lib32-gamemode
      cli:
        - yay
        - unzip
        - wget
        - fd
        - stow
        - alacritty
        - fish
        - bash
        - upower
        - htop
        - yt-dlp
        - yazi
        - poppler
        - rg
        - jq
        - fzf
        - git
        - eza
        - ripgrep
        - starship
        - zoxide
      dev:
        languages:
          - npm
          - ninja
          - gcc
          - cmake
          - jdk-openjdk
          - python3
          - python-pip
          - go
          - rust
        language_servers:
          - clang
          - gopls
          - rust-analyzer
          - ansible-language-server
          - lua-language-server
          - yaml-language-server
          - taplo # toml lsp
        tools:
          - lldb # c+rust debug adpater
          - zellij
          - helix
          - neovim
          - lazygit
          - wireshark-qt
          - docker
          - docker-compose  
    aur_packages:
      - aur-auto-vote-git 
      - xpadneo-dkms # xbox controller support
      - proton-ge-custom-bin
      - aura-bin 
      - floorp-bin 
      - heroic-games-launcher-bin  
      - steamtinkerlaunch 
      - minecraft-launcher 
      - macchina-bin 
      - lua-format 
      - clang-format-static-bin
      - lazydocker-bin 
      - catppuccin-gtk-theme-macchiato
      - qt5-styleplugins
      - timeshift-autosnap  

- name: install packages arch
  when: ansible_distribution in [ "Archlinux" ]
  loop:
      - "{{ packages.window_manager }}"
      - "{{ packages.networking_tools }}"
      - "{{ packages.apps }}"
      - "{{ packages.gaming }}"
      - "{{ packages.cli }}"
      - "{{ packages.dev.tools }}"
      - "{{ packages.dev.languages }}"
      - "{{ packages.dev.language_servers }}"
  package:
    name: "{{ item }}"
      
- name: Install aur packages with yay via aur plugin
  when: ansible_distribution in [ "Archlinux" ]
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present # just installs and does not upgrade
    use: yay
    name: "{{ aur_packages }}"
      

- name: install packages debian
  when: ansible_distribution in [ "Debian", "Pop!_OS", "Ubuntu" ]
  package:
    name:
      - None

- name: install packages opensuse
  when: ansible_distribution in [ "OpenSuse" ]
  package:
    name:
      - None
