---
- name: Install ansible galaxy content
  loop_control:
    loop_var: content
  with_items:
    - type: collection
      name: kewlfft.aur
  community.general.ansible_galaxy_install:
    type: "{{ content.type }}"
    name: "{{ content.name }}"
