---
- name: set display manager
  become: true
  systemd_service:
    name: greetd
    state: started
    enabled: true

- name: start grub with new snapshot entries
  become: true
  systemd_service:
    name: grub-btrfsd
    state: restarted
    enabled: true

- name: enable bluetooth
  become: true
  systemd_service:
    name: bluetooth
    state: started
    enabled: true
