---
- name: create libvirt group
  ansible.builtin.group:
    name: libvirt
    state: present

- name: add user groups
  ansible.builtin.user:
    name: sawyer
    append: true
    groups:
      - wheel
      - adm
      - games
      - log
      - rfkill
      - sys
      - gamemode
      - qemu
      - libvirt
      - uucp
      - audio
      - disk
      - input
      - scanner
      - storage
      - video
      - openvpn
      - docker
      - wireshark

- name: Create the `aur_builder` user
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    mode: 0644
    validate: "visudo -cf %s"
