- name: add user to gamemode group
  ansible.builtin.user:
    name: sawyer
    groups: 
      - gamemode

- name: find gamescope path
  shell: which gamescope
  register: gamescope

- name: escalate gamescope permissions
  become_user: root
  shell: setcap 'CAP_SYS_NICE=eip' \ "{{ gamescope.stdout }}"

- name: create ansible user
  user: name=ansible uid=900

- name: copy sudoers_ansible
  copy: src=tasks/files/sudoers_ansible dest=/etc/sudoers.d/ansible owner=root group=root mode=0440

- name: Create the `aur_builder` user
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0644
    validate: 'visudo -cf %s'
