[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
command = "alacritty --class alcritty-dropterm"
class = "alacritty-dropterm"
size = "75% 60%"
margin = 50
unfocus = "hide"
max_size = "1920px 100%"

[scratchpads.volume]
animation = "fromTop"
command = "pavucontrol-qt"
class = "pavucontrol-qt"
lazy = true
size = "40% 90%"
unfocus = "hide"
