long_uptime = true
long_shell = false
long_kernel = false
current_shell = true
physical_cores = true
theme = "Oxygen"
show = [
  "Kernel",
  "Distribution",
  "WindowManager",
  "Resolution",
  "Terminal",
  "Uptime",
  "ProcessorLoad",
  "Memory",
]
